version: '3.8'

services:
  scraper-manager:
    build:
      context: ./Scraper-Manager
      dockerfile: Dockerfile
    container_name: scraper-manager
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Scraper-Manager:/app
    environment:
      - ENVIRONMENT=development
    networks:
      - scraper-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  scraper-dashboard:
    build:
      context: ./Scraper-Dashboard
      dockerfile: Dockerfile
    container_name: scraper-dashboard
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./Scraper-Dashboard:/app
    depends_on:
      - scraper-manager
    networks:
      - scraper-network

  # Scraper-Instance template (not started by default)
  scraper-instance:
    build:
      context: ./Scraper-Instance
      dockerfile: Dockerfile
    image: scraper-instance:latest
    profiles: ["manual"]  # This prevents it from starting automatically
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge
